### ISSUE TITLE
cy.checkA11y() is accepting only 2 arguments I need to set skipFailures to 'True'

### ISSUE THREAD

**Issue by Pawanesh1** [avanslaars/cypress-axe#39]
I need to disables assertions based on violations and only logs violations to a report, so was trying to pass 4 arguments to cy.checka11y() as described by @avanslaars , but got an error 

**0-2 arguments expected, got 4**

package.json
  "devDependencies": {
    "@type/cypress-axe":"0.4.0"
    "cypress-axe": "^0.8.1"
  }

**Comment by avanslaars** [comment]
I would need some context to see where the error is coming from and what your actual test code looks like. Currently, `cy.checkA11y()` accepts 4 arguments, with `skipFailures` being the last. 
https://github.com/avanslaars/cypress-axe/blob/master/src/index.js#L17-L21

**Comment by Pawanesh1** [comment]
The problem starts with initial setup I suppose. 
My cy.injectAxe() and cy.checka11y() commands are not  recognized. Here is what I did 
1. I already had cypress in installed  - "cypress": "^4.1.0"
2. I ran the command npm i -D cypress-axe
3 added import 'cypress-axe' to Cypress/support/index.js file
4. update tests to include cy.injectAxe() in beforeall, after cy.visit()
but it gave me error : 
"Property 'injectAxe' does not exist on type 'cy & EventEmmitter' "
Then I ran the command: npm i @types/cypress-axe and the error was resolved, but now cy.checkA11y() accepts only 2 arguments.

**Comment by vasanthkumar258** [comment]
@avanslaars , I hope this is because of typing file is not updated with skipFailures fix in https://github.com/avanslaars/cypress-axe/pull/21/

**Comment by sapegin** [comment]
Do you still have this problem?
